### ISSUE TITLE
Suggestion Cash et Flèche du Menu

### ISSUE THREAD

**Issue by DjeyMute** [PYRRH4/BettingGames#5]
Comme convenu en mp je viens déposer la mes petites idées.
(DONE) Donc ce serait pour le cash de pouvoir choisir le début de décompte car en ce moment il est bloqué à 0.60
Et de pouvoir désactiver la flèche qui permet aux joueurs de revenir dans le menu et de jouer à n'importe quel jeu sans avoir à bouger.

**Comment by PYRRH4** [comment]
Ok ^^ "Jouer à n'importe quel jeu sans avoir à bouger", tu veux dire quoi par là ?

**Comment by DjeyMute** [comment]
Je veux dire que j'ai connecté chaque mini-jeu à un npc et du coup avec la flèche ils peuvent revenir en arrière et en faire un autre ^^

**Comment by PYRRH4** [comment]
Ok, jai ajouté l'option 'start_value' pour le CRASH, ça sera pour la prochaîne MAJ. Pour l'item de retour, c'est déjà possible en fait ^^ Dans 'config.yml', tu peux supprimer la section 'back_item' et normalement la flèche n'apparaît pas dans le menu !

**Comment by DjeyMute** [comment]
J'ai déja essayé de la supprimé et sa ne fait rien ^^
