### ISSUE TITLE
bug duplication new

### ISSUE THREAD

**Issue by FyFou57** [PYRRH4/BettingGames#8]
### Type

> Put a X where you want

- [x] Bug with BettingGames/PyrCore
- [ ] Incompatibility with another plugin
- [ ] Integration for another plugin
- [ ] Suggestion
- [ ] Other

### Description

Quand une partie de pierre feuille ciseau est annulé le joueur qui na pas choisi (et qui donc perd) ne 
perd pas la money

https://www.youtube.com/watch?v=mzgDRt-hvN0&feature=youtu.be

**Comment by FyFou57** [comment]
"Le Pierre feuille ciseau, quand deux personnes lancent une partie mais ne jouent pas de suite la partie s'annule mais le menu reste quand même, à partir de ce moment là les deux joueurs jouent n'importe lequel et le gagnant gagne la partie mais le perdant perd pas d'argent. Certaines personnes se sont amusées à ça hier quand j'ai signalé le bug...
Faut vraiment arreter de le mettre, 3 fois que tu le mets, 3 fois que y'a des usebugs avec."

**Comment by PYRRH4** [comment]
Pour la partie qui s'annule c'est normal, les mises sont remboursées ; mais c'est effectivement plus malin de faire perdre le joueur qui a mis trop longtemps à choisir. Pour le bug de dupli, je regarde.
